version: "3.8"

services:
  postgres:
    container_name: oliva-sso-db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      PGDATA: /data/postgres
    ports:
      - "5435:5435"
    restart: unless-stopped