env: "local"
grpc:
  port: 50051
  timeout: 5s
postgres:
  host: "172.21.0.2"
  user: "admin"
  password: "admin"
  dbname: "oliva_auth"
  port: "5432"
  sslmode: "disable"
  timezone: "Asia/Shanghai"